TesteWeb/Controllers/ArquivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Reports;
using Reports.DataSets;
using System.IO;
using System.Text.RegularExpressions;
using TesteWeb.Models;
namespace TesteWeb.Controllers
{
    public class ArquivoController : Controller
    {
        // GET: Arquivo
        public ActionResult Index()
        {
            return View();
        }
        // Envio de cada arquivo
        [HttpPost]
        public ActionResult EnvioArquivo(HttpPostedFileBase file, String nome)
        {
            try
            {
                if(nome == "teste")
                {
                    throw new Exception("Zaz");
                }

                String caminhoGravacaoArquivos = @"C:\caminhoTeste\";
                String extensao = String.Empty;
                String mimeType = String.Empty;
                mimeType = file.ContentType;
                extensao = this.GetExtensionByMimeType(mimeType);
                String nomeArquivoGerado = this.GerarNomeArquivo(nome);
                String nomeArquivo = String.Format("{0}{1}.{2}", caminhoGravacaoArquivos, nomeArquivoGerado, extensao);
                // Obtendo bytes
                byte[] fileData = null;
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    fileData = binaryReader.ReadBytes(file.ContentLength);
                }
                // Escrevendo bytes no caminho especificado
                using (FileStream fileStream = new FileStream(nomeArquivo, FileMode.Create))
                {
                    for (int i = 0; i < fileData.Length; i++)
                    {
                        fileStream.WriteByte(fileData[i]);
                    }
                }
                return Json(new { msg = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw ex;
                //return Json(new { msg = "NOK" }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public ActionResult RemoverArquivo(String nome)
        {
            String caminhoGravacaoArquivos = @"C:\caminhoTeste\";
            String nomeArquivoParticipante = this.GerarNomeArquivo(nome); // Montar nome com base nas informações do participante
            String caminhoAPesquisar = String.Format(@"^{0}.*$", nomeArquivoParticipante);
            Regex exp = new Regex(caminhoAPesquisar);
            try
            {
                // Listar conteúdo do diretório
                String[] arquivos = Directory.GetFiles(caminhoGravacaoArquivos);
                foreach (var arq in arquivos)
                {
                    String nomeArquivo = arq.Replace(caminhoGravacaoArquivos, "");
                    bool encontrou = exp.IsMatch(nomeArquivo);
                    if (encontrou)
                    {
                        // remove o arquivo
                        String caminhoArquivoCompleto = String.Format("{0}{1}", caminhoGravacaoArquivos, nomeArquivo);
                        System.IO.File.Delete(caminhoArquivoCompleto);
                        break;
                    }
                }
                return Json(new { msg = "OK" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { msg = "NOK" }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult ImprimirArquivo(String Nome)
        {
            try
            {
                String caminhoArquivo = @"C:\Users\p017432\Downloads\spinner.gif";
                string mimeType = MimeMapping.GetMimeMapping(caminhoArquivo);
                byte[] bytes = this.LerBytesArquivo(caminhoArquivo);
                byte[] relatorio = bytes;
                var result = (FileContentResult)File(relatorio, mimeType);
                string nomeRelatorio = string.Empty;
                String extensao = this.GetExtensionByMimeType(mimeType);
                if (extensao.Length == 0)
                {
                    throw new Exception("Extensão não encontrada");
                }
                nomeRelatorio = String.Format("arquivo_teste.{0}", extensao);
                result.FileDownloadName = nomeRelatorio;
                return result;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        private String GerarNomeArquivo(String nome)
        {
            return nome;
        }
        private String GetExtensionByMimeType(String mimeType)
        {
            String extensao = String.Empty;
            switch (mimeType)
            {
                case "application/pdf":
                    extensao = "pdf";
                    break;
                case "application/msword":
                    extensao = "doc";
                    break;
                case "image/gif":
                    extensao = "gif";
                    break;
                case "image/png":
                    extensao = "png";
                    break;
                case "image/jpeg":
                    extensao = "jpg";
                    break;
                default:
                    extensao = String.Empty;
                    break;
            }
            return extensao;
        }
        private byte[] LerBytesArquivo(String caminho)
        {
            byte[] bytes = null;
            using (FileStream fsSource = new FileStream(caminho,
                    FileMode.Open, FileAccess.Read))
            {
                bytes = new byte[fsSource.Length];
                int numBytesToRead = (int)fsSource.Length;
                int numBytesRead = 0;
                while (numBytesToRead > 0)
                {
                    // Read may return anything from 0 to numBytesToRead.
                    int n = fsSource.Read(bytes, numBytesRead, numBytesToRead);

                    // Break when the end of the file is reached.
                    if (n == 0)
                        break;

                    numBytesRead += n;
                    numBytesToRead -= n;
                }
                numBytesToRead = bytes.Length;
            }
            byte[] relatorio = bytes;
            return relatorio;
        }
    }
}

TesteWeb/Views/Shared/_Arquivo.cshtml
@using TesteWeb.Controllers
@using TesteWeb.Models
@{
    var urlEnvioArquivo = Url.Action("EnvioArquivo", "Arquivo");
    var urlRemocaoArquivo = Url.Action("RemoverArquivo", "Arquivo");
    List<ArquivoModel> arquivosExistentes = new List<ArquivoModel>();
    // arquivosExistentes.Add(new ArquivoModel() { Nome = "teste" });
    List<ArquivoModel> listaArquivos = arquivosExistentes;
    int quantidadeMinimaArquivos = 2;
}
@model int?
<!-- dropzone -->
@if (Model.HasValue)
{
    var desc = Model.Value;
    <h1>Identificador: @desc</h1>
}
<form id="frmDropZone" method="post">
    <div id="dropZona" class="col-md-12">
        <div class="row">
            <div class="col-md-2 form-group">
                <label for="txtNome">Nome</label>
                <input class="form-control" name="txtNome" id="txtNome" />
            </div>
            <div class="col-md-2 form-group">
                <button class="clicavel btn btn-default" style="margin-top: 1.7em;">Anexar arquivo</button>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <table id="tblArquivos" class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Comprovante</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (listaArquivos != null && listaArquivos.Count() > 0)
                        {
                            int x = 1;
                            <tr class="antigo">
                                @foreach (var c in listaArquivos)
                                {
                                    <td>@c.Nome </td>
                                    <td><a target="_blank" href="@Url.Action("ImprimirArquivo", "Arquivo", new { Nome = c.Nome })">Link</a></td>
                                    <td><a class="lnkExclusao" data-contador="@x" data-nome="@c.Nome" href="#" onclick="javascript: removerArquivo(this)">Excluir</a></td>
                                    x++;
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-2 form-group">
                <button type="button" name="btnEnviarServidor" id="btnEnviarServidor" class="btn btn-default">Enviar pro servidor</button>
            </div>
        </div>
    </div>
</form>

<script type="text/javascript">
    var DropzoneDocumento = {};
    var urlArquivo = "@urlEnvioArquivo";
    var quantidadeMinimaArquivos = @quantidadeMinimaArquivos;
    var formularioArquivoValido = false;
    $(document).ready(function () {
        $("button").click(function (evt) { evt.preventDefault(); });
        // todo: DropZone
        DropzoneDocumento = new Dropzone("#dropZona", {
            url: urlArquivo,
            clickable: ".clicavel",
            acceptedFiles: ".pdf, .jpg, .png",
            maxFilesize: 20,
            //maxFiles: 3, quantidade máxima por tipo de documento
            acceptedFiles: "image/*, application/pdf",
            dictRemoveFileConfirmation: "Quer mesmo excluir o arquivo?",
            dictFileTooBig: "Tamanho máximo de cada arquivo: 20MB",
            uploadMultiple: false,
            parallelUploads: 1,
            autoProcessQueue: false, // Envio ao servidor se dá de forma manual
            //autoProcessQueue: true, // Envio ao servidor se dá de forma automática
            init: function () {
                var self = this;
                // Eventos aqui
                self.on("addedfile", function (file) {
                    console.log(file);
                    console.log("Arquivo adicionado");
                    file.nome = $("#txtNome").val();
                    ExibirListaArquivos(file);
                });

                self.on("processing", function (file) {
                    console.log("Arquivo em processamento");
                    console.log(file);
                });

                self.on("removedfile", function (file) {
                    console.log("Arquivo removido");
                    console.log(file);
                });

                self.on("maxfilesexceeded", function (file) {
                    console.log("Excedido número máximo de uploads");
                });

                self.on("sending", function (file, xhr, formData) {
                    console.log("Adicionando novos parâmetros");
                    formData.append("nome", file.nome);
                });

                self.on("queuecomplete", function () {
                    console.log("Upload completo de documentos");
                    /*if (DropzoneDocumento.getAcceptedFiles().length > 0) {
                        DropzoneDocumento.processQueue();
                    }*/
                    console.log(DropzoneDocumento);
                    // Reprocessar arquivos com erro
                    let listaArquivosEnviados = DropzoneDocumento.getAcceptedFiles();
                    let listaArquivosComErro = listaArquivosEnviados.filter(x => x.status == "error");
                    console.log(listaArquivosComErro);
                    if (listaArquivosComErro.length > 0) {
                        ReprocessarFila(listaArquivosComErro);
                    }                    
                });

                self.on("complete", function (file) {
                    console.log("Upload de document completo");
                    console.log(file);
                    if (file.status == "success") {
                        self.processQueue();
                    } else if (file.status == "error") {
                        console.log("Parar processamento da fila");
                        //file.status
                    }                    
                });
            },
        });
        $("#btnEnviarServidor").click(function (evt) {
            evt.preventDefault();
            enviarArquivosServidor();
        });
        $("button[data-formulario-arquivo-valido='true']").click(function (ev) {
            ev.preventDefault();
            console.log("Validar formulário de arquivos");
            //$(this).off("click").on("");
            //formularioArquivoValido = true
            retornoValidacaoArquivos = ValidarArquivos();
            formularioArquivoValido = retornoValidacaoArquivos[0];
            if (formularioArquivoValido == false) {
                alert(retornoValidacaoArquivos[1]);
            }
        });
    });
    function ReprocessarFila(listaArquivosComErro) {
        for (let i = 0; i < listaArquivosComErro.length; i++) {
            listaArquivosComErro[i].status = "queued";
            listaArquivosComErro[i].upload.bytesSent = 0;
            listaArquivosComErro[i].upload.progress = 0;
        }        
        console.log(DropzoneDocumento.getAcceptedFiles());        
    }
    function ExibirListaArquivos(file) {
        let arquivos = DropzoneDocumento.getAcceptedFiles();
        $("#tblArquivos tbody > .novo").empty();
        let templateHtml = "";
        if (file != null) {
            templateHtml += `<tr class="novo">
        <td>${file.nome}</td>
        <td>Baixar</td>
        <td><a data-nome="${file.nome}" href="#" onclick="javascript: removerArquivo(this)">Excluir</a></td>
        </tr>`;
        }
        if (arquivos != null && arquivos.length > 0) {
            for (var c = 0; c < arquivos.length; c++) {
                templateHtml += `<tr class="novo">
                <td>${arquivos[c].nome}</td>
                <td>Baixar</td>
                <td><a data-contador="${c+1}" data-nome="${arquivos[c].nome}" href="#" onclick="javascript: removerArquivo(this)">Excluir</a></td>
                </tr>`;
            }
        }
        $("#tblArquivos tbody").append(templateHtml);
    }
    function removerArquivo(obj) {
        console.log(obj);
        var attr_nome = $(obj).attr("data-nome");
        var attr_contador = $(obj).data("contador");
        console.log(attr_nome);
        var arquivosDocumento = DropzoneDocumento.getAcceptedFiles();
        let encontrou_lista = false;
        for (var i = 0; i < arquivosDocumento.length; i++) {
            if (arquivosDocumento[i].nome == attr_nome) {
                encontrou_lista = true;
                console.log("LIQUIDAR!!");
                console.log(arquivosDocumento[i]);
                DropzoneDocumento.removeFile(arquivosDocumento[i]);
                ExibirListaArquivos(null);
                break;
            }
        }
        if (encontrou_lista == false) {
            $("#tblArquivos tbody tr.antigo").each(function (i, v) {
                let linha = $(v);
                console.log(linha);
                let nomeLinha = linha.find("a.lnkExclusao").data("nome");
                console.log(nomeLinha);
                if (nomeLinha == attr_nome) {
                    // Implementar exclusão do arquivo no servidor
                    removerArquivoServidor(nomeLinha, $(v));
                }
            });
        }
    }
    function removerArquivoServidor(nome, elemento) {
        $.ajax({
            url: "@urlRemocaoArquivo",
            dataType: "json",
            data: { nome: nome },
            method: "POST",
            success: function (data) {
                if (data.msg == "OK") {
                    elemento.remove();
                }
            },
            error: function (xhr, status,) { }
        });
    }
    function enviarArquivosServidor() {
        if (DropzoneDocumento.getAcceptedFiles().length > 0) {
            DropzoneDocumento.processQueue();
        }
    }

    function ValidarArquivos() {
        let quantidadeArquivosExistentes = $("#tblArquivos tbody tr").length;
        console.log(quantidadeArquivosExistentes);
        if (quantidadeArquivosExistentes < quantidadeMinimaArquivos) {
            return [false, "Deve ter a quantidade mínima de arquivos"];
        }
        // Verificar se fila de envio do dropzone está concluído
        let quantidadeArquivosFilaEnvioServidor = DropzoneDocumento.getQueuedFiles().length;
        let quantidadeArquivosEmMemoria = DropzoneDocumento.getAcceptedFiles().length;
        //console.log(quantidadeArquivosFilaEnvioServidor);
        //console.log(quantidadeArquivosEmMemoria);
        if (quantidadeArquivosEmMemoria > 0 && quantidadeArquivosFilaEnvioServidor > 0) {
            return [false, "Existem arquivos a serem enviados ao servidor."];
        }
        return [true, "envio de arquivos feito com sucesso"];
    }
</script>

TesteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/materialize/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    @*
        <link rel="stylesheet" media="print" href="@Url.Content("~/Content/print.css")" />
    *@


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Grafico", "Grafico", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/dropzone")
    @Scripts.Render("~/materialize/js")
    @Scripts.Render("~/printThis/js")
    @RenderSection("scripts", required: false)
</body>
</html>